### PR TITLE
feat: Table of Contents Component

### LINKED ISSUE #95: [Feature Request] Table of Contents and Table of Child Pages
Loving this project so far, awesome work!

I'm sure this ask is already on your roadmap but just in case it isn't: It would be really great to be able to add a Table of Contents that operates on headers, as well as a Table of Children that lists nested pages.

### LINKED ISSUE #204: [Feature Request]: Table of Content macro
Good evening

**Congratulations for your great work, although it is a beta version, the SW is already working very well.**

**This is probably a very common / often used feature:**
It would be great if one could also **create a table of contents from the headers** on a page.

Thanks a lot, kind regards,
Thomas

### PR DESCRIPTION
**Pull request by Shadowfita**
This pull request adds an mvp table of contents component and resolves #204 and resolves #95 . I plan to add a node menu for style options, unsure if you would like to wait for those additions before considering.

I did some testing of the headings filter loop and it seldomly fires, so there shouldn't be a performance concern there. Happy to amend to match any codebase conventions however.

There may be some unnecessary code in the editor-ext lib, I'm not extremely familiar with tiptap editor extensions.

### CODE REVIEW

**Comment by Shadowfita** [comment]
image

image

**Comment by Shadowfita** [comment]
Thanks @Philipinho. I hope it can be of value. May I ask what your reservations are outside of having it across all pages rather than a node extension?

**Comment by Philipinho** [comment]
@Shadowfita I would not want to make this an editor node when we can have a global TOC available on all pages by default. It saves us more nodes to maintain.
If there are more requests in the future, I could reconsider.

**Comment by Shadowfita** [comment]
I have rebased my fork and created the appropriate branches for my pull requests, I will be re-opening the PR from the correct branch for this feature for future consideration @Philipinho , no action to take, just an FYI.

**Pull request closed without merging**
